name: Reusable - Commitlint

on:
  workflow_call:
    inputs:
      configFile:
        description: Caminho do arquivo de config do commitlint (opcional)
        required: false
        type: string

jobs:
  commitlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout do repositório chamador
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commits com commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ${{ inputs.configFile }}
